services:
  - type: web
    name: staff-portal
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    
    # Environment variables
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_ENV
        value: production
    
    # Security headers
    headers:
      # Prevent clickjacking attacks
      - path: /*
        name: X-Frame-Options
        value: DENY
      
      # Prevent MIME type sniffing
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      
      # Control referer information
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      
      # Enable XSS protection
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      
      # Restrict browser features
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=(), payment=(), usb=()
      
      # Content Security Policy (adjust based on your needs)
      - path: /*
        name: Content-Security-Policy
        value: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'none';
      
      # Force HTTPS (if using SSL)
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains; preload
      
      # Cache static assets aggressively
      - path: /static/css/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      
      - path: /static/js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      
      - path: /static/media/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      
      # Cache images for shorter period
      - path: /images/*
        name: Cache-Control
        value: public, max-age=86400
      
      # Don't cache HTML files
      - path: /
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    
    # SPA routing - redirect all requests to index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    
    # Health check endpoint (optional)
    healthCheckPath: /
    
    # Auto-deploy settings
    autoDeploy: true
    branch: main